### ISSUE TITLE
111

### ISSUE THREAD

**Issue by hhhhd1231** [Tamiflu233/DingVideo#26]
uu 我可以拉下来学习一下吗 本来我是想参加比赛的 但是时间不允许 因为我是10月30号才看到比赛的信息 但是成员觉得时间不够就不做了 但我还是很想学习一下 并且查看具体一些实现的功能

**Comment by Tamiflu233** [comment]
可以哈，不过后端的数据库啥的换成你们自己的就行

**Comment by hhhhd1231** [comment]
感谢感谢！

**Comment by hhhhd1231** [comment]
uu能给个SQL执行脚本不

**Comment by Tamiflu233** [comment]
> uu能给个SQL执行脚本不

sql文件已上传

**Comment by hhhhd1231** [comment]
感谢！&nbsp;


1362419827
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月14日(星期二) 中午12:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tamiflu233/DingVideo] 111 (Issue #26)





  
uu能给个SQL执行脚本不
  
sql文件已上传

**Comment by hhhhd1231** [comment]
关于点赞的，关注这一块这个发行的版本是不是没有特别的完善呀

**Comment by Tamiflu233** [comment]
> 关于点赞的，关注这一块这个发行的版本是不是没有特别的完善呀

是的，当时来不及做完
